# ==============================================================================
#                      MangoWC 极简实用版配置文件
# ==============================================================================

# [配置重载]
# 按 SUPER+r 运行语法检查并热重载桌面配置
bind=SUPER,r,spawn_shell,bash ~/.config/mango/scripts/config_check.sh
bind=SUPER,r,reload_config

# [核心工具与终端启动]
# Alt + Enter 或 Super + Enter：启动 foot 终端
bind=Alt,Return,spawn,foot
bind=SUPER,Return,spawn,foot
# Super + o：启动应用启动器 (Rofi)
# bind=SUPER,o,spawn,rofi -config ~/.config/mango/rofi/config.rasi -show drun
bind=SUPER,o,spawn,fuzzel
bind=SUPER,d,spawn,~/.config/fuzzel/search.sh
# Ctrl+Super+Enter：终端内打开 yazi 文件管理器
bind=CTRL+SUPER,Return,spawn,foot -e yazi

# [窗口关闭与退出]
# Alt + q：关闭当前聚焦的窗口
bind=ALT,q,killclient,

# [窗口焦点与位置控制]
# Alt + 方向键：切换窗口焦点
bind=ALT,Left,focusdir,left
bind=ALT,Right,focusdir,right
bind=ALT,Up,focusstack,prev
bind=ALT,Down,focusstack,next

# Super+Shift+方向键：对调平铺窗口的位置
bind=SUPER+SHIFT,Up,exchange_client,up
bind=SUPER+SHIFT,Down,exchange_client,down
bind=SUPER+SHIFT,Left,exchange_client,left
bind=SUPER+SHIFT,Right,exchange_client,right

# [窗口状态控制]
# Alt + Tab：全局窗口预览 (Overview)
bind=ALT,Tab,toggleoverview,0
# Super + \ ：切换当前窗口 悬浮/平铺 状态
bind=SUPER,backslash,togglefloating,
# Super + f ：窗口最大化 (保留状态栏和边框)
bind=SUPER,f,togglemaximizescreen,
bind=SUPER,k,togglefakefullscreen,
# Alt + f：标准真全屏 (覆盖状态栏)
bind=ALT,f,togglefullscreen,
# Super + g：切换全局窗口状态
bind=SUPER,w,toggleglobal,
# 备用注释：
# bind=SUPER,p,toggle_scratchpad

# [通用布局切换]
# 备用注释：
# bind=SUPER,n,switch_layout
# bind=ALT+SHIFT,R,togglegaps

# [工作区/标签切换 (1-9)]
# Ctrl + 1~9：直接跳转到 1-9 号工作区视图
bind=Ctrl,1,view,1,0 ... bind=Ctrl,9,view,9,0
# Alt + 1~9：将当前窗口移动到对应工作区
bind=Alt,1,tag,1,0  ... bind=Alt,9,tag,9,0
# Super + 左/右方向键：单步切换到相邻的工作区
bind=SUPER,Left,viewtoleft,0
bind=SUPER,Right,viewtoright,0

# [核心功能与硬件调节]
# Ctrl+Alt+a：区域截图并调用 satty 编辑器
bind=SUPER,g,spawn,/usr/local/bin/wl-screenshot area
# Super + h：隐藏/显示 Waybar 状态栏
bind=SUPER,h,spawn,bash ~/.config/mango/scripts/hide_waybar_mango.sh
# Super + l：锁定屏幕
bind=SUPER,l,spawn,hyprlock
# Ctrl+Alt+\ ：展开/收起通知中心栏
bind=CTRL+ALT,backslash,spawn,swaync-client -t

# 键盘多媒体硬件键音量调节
bind=none,XF86AudioRaiseVolume,spawn,~/.config/mango/scripts/volume.sh up
bind=none,XF86AudioLowerVolume,spawn,~/.config/mango/scripts/volume.sh down
# 键盘多媒体硬件键屏幕亮度调节
bind=none,XF86MonBrightnessUp,spawn,~/.config/mango/scripts/brightness.sh up
bind=none,XF86MonBrightnessDown,spawn,~/.config/mango/scripts/brightness.sh down

# [最常用鼠标绑定]
# Super + 鼠标左键：按住拖动即可移动悬浮窗口
mousebind=SUPER,btn_left,moveresize,curmove
# Super + 鼠标右键：按住拖动即可缩放悬浮窗口大小
mousebind=SUPER,btn_right,moveresize,curresize

