# ~/.config/foot/foot.ini

[main]
# 字体设置：支持回退字体
font=JetBrainsMono Nerd Font:size=14, JetBrainsMono Nerd Font:size=14
# 窗口内边距
pad=8x8
# 终端类型，默认 foot，兼容性问题可改为 xterm-256color
term=foot
# include=~/.config/foot/dank-colors.ini
selection-target=both

[colors]
# 透明度 (0.0 - 1.0)
alpha=1.0
# 基础配色
background=161616
# foreground=c0caf5

[scrollback]
# 滚动行数限制 (0 表示无限)
lines=10000

[cursor]
# 光标样式: block, beam, underline
style=block
blink=yes

[mouse-bindings]
select-extend=none
primary-paste=BTN_RIGHT
