# uosc provides seeking & volume indicators (via flash-timeline and flash-volume commands)
# if you decide to use them, you don't need osd-bar
osd-bar=no

# uosc will draw its own window controls and border if you disable window border
border=no
panscan=1.0

# 设置播放器默认字体（影响 OSC 和 OSD 提示）
osd-font='Microsoft YaHei'
# 如果有字幕显示问题，顺便设置字幕字体
sub-font='Microsoft YaHei'
