[main]
font=JetBrainsMono Nerd Font:size=16, Noto Sans CJK SC:size=14
icon-theme=Papirus
fields=name,generic,comment
lines=10
width=45
horizontal-pad=15
vertical-pad=15
inner-pad=8
fields=name,generic,comment,keywords
prompt=" "
# anchor=top-left
layer=top
keyboard-focus=on-demand

# ================= 核心功能设置 =================
# 1. 允许其他区域获取焦点，配合实现失焦自动关闭
# focus-mode=on-demand
# 2. 当检测到键盘或鼠标焦点离开 Fuzzel 时，立刻自动隐退销毁窗口
exit-on-keyboard-focus-loss=yes

# ================= 极客青配色方案 =================
[border]
radius=12
width=2

[colors]
# background=24273add
# background=303446dd
background=1e1e2eff
text=cad3f5ff
prompt=b8c0e0ff
placeholder=8087a2ff
input=ffffffff
match=f53c3cff
selection=08bdbaff
selection-text=000000ff
selection-match=f53c3cff
counter=8087a2ff
border=08bdbaff
