[LightDM]
run-directory=/run/lightdm

[Seat:*]
greeter-session=lightdm-slick-greeter
greeter-hide-users=false
user-session=xfce
session-wrapper=/etc/lightdm/Xsession
display-setup-script=/etc/lightdm/display-setup.sh

[XDMCPServer]

[VNCServer]
